version: "3.7"

services:

  ignite_rentx_database:
    image: postgres
    container_name: ignite_rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: ignite
      POSTGRES_DB: rentx
    volumes:
      - pgdata:/data/postgres

  ignite_rentx:
    image: claudneysessa/rentx
    build: .
    container_name: ignite_rentx
    ports:
      - "3333:3333"
      - "3339:3339"
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    name: pgignite_rentx_pgdata
    driver: local
